# Configuration for paper_analyses_v2 project

n_steps: 50
model_name: "gpt2-large"
# model_name: "google/vit-base-patch16-224"
# model_name: "resnet50"

text: 
  shared_context: "The house was"
  pairs:
    - ["big", "in"]
    - ["big", "large"]

image:
  shared_image: "https://farm4.staticflickr.com/3385/3204622086_bee54dfb59_z.jpg"
  pairs:
    - [
        "https://farm4.staticflickr.com/3385/3204622086_bee54dfb59_z.jpg",  # cat
        "https://farm8.staticflickr.com/7028/6656578667_9011675967_z.jpg" # dog
      ]
    - [
        "https://farm4.staticflickr.com/3280/3204622086_bee54dfb59_z.jpg",  # cat
        "https://farm3.staticflickr.com/2335/2406707284_04264023a9_z.jpg" # another cat
      ]
  shared_image_id: "cat1_coco"
  pairs_ids:
    - ["cat1_coco", "dog1_coco"]
    - ["cat1_coco", "cat2_coco"]
  



# images can be found in the Coco dataset: https://cocodataset.org/#explore